language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - $HOME/.m2
sudo: false
install: true
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: E3XLcCfm5fw54pyQNIPTUtI/Wah9bjatS8fs8iGUd1F1Rx8SDBQUhtsYAvxR//oKOIsa1ktyfxG+owh1L4zxqP9YYfQKFZZqaZPgRv7zw9sAaK0kcVJRfC0vfzAzceC9/Y2GBJKkTnFnfDCDjL4Xzgxd6yIDp7aOlFBXem0dGKwBNlJMrJDdFk223qHA1gWTGNKMqVapJ0sx9FwoBCrwPhwQD2DDemYRxIg6oCxEd0nqgdIoGFs4TfKQgZFIZ3XJesS+6/7pUl1DqPDOdsm32bLjCrUJD2uSzm6Pi7qy4LdF2zZFEpPKaf6jFzAq10YHeQgJupkqFrr8Ix17QAG2UnZ3FoM9vw5BGOMJwaBukK8lnIxoST4AQHJh1XQwwK27p9OEHdEBvcU4lHDvSvSSl9I+WeaxIaD9sORxYb417nu16VWxe5MTXGVVrFLB6P7p3Coz+tkn6C/OXYlzmrzVpDs5JDl3KRlQh3Nnv+psu8KX3JGNx8uiIWcrWMkP7DlVwqSWwZ7pAgUe92JRYKAvK269vyb0fMeLeaydhh/uCcLr9tp+Y9/YsOdAmUkv87WjFjKqqIfRv01ZrpqOlPslNOorA/45sUq33wu2MTiF+Bpe3QuLSVpUO47c3xbmWREk4TZmYwa0gyDaUa3IrmuUNxwsjUfnfsS+cjYSgLvbdcE=
  - secure: qGYcv5OXyY4mLYknF9141pj0Ux9hN7prqChWITgULYNgyNXkP+RLXvS8eNTRth8Z9d0Phw15SIELlWEsCZSgKyEEfVanrUep79OvckgK9jjm9h9aLfze2g5LXqyq9LM6UZRPegJMboyYyEsF/A957VPk/1LBOHjCDZxEquiBeXkEG1A+Hj9EpQ9ekYJK52tLvCvCo2U0H2U1qCxig8C1Lkbh9Dp5exJPPeIXD0WKxrpYlCKcfZEukp3iOyp2bDoNay+ETzafy7g8OooWWN6a00R3xjckyNt/ilYNsNIZXv0DJoyXFnWZ8VVoONXAxsTufD9a3QeuSXJtLIP+UJKPGR9e0oxUZKOJIv/PZ4qQ1iBd7cgmprr74xMaikeAdjIwsAoW+m4cm5WQelavNMGHB132Yy8osVeMapT9JJxjy/M6vk6Na5SN8qGrZvAG5GxP1yucvBHdDqEnioS9xnWKvR3AfImJxsmAYIC7I/RPuM0PLLqMOo4JeRvhRHg+/zUaQNOWlc5MRMnQapVQTJ0Sst3ScqoSCQR1JHzqj3gO8SXxcLioRRuRq2RwPkpkdLL1ufKJNdlLRusZlFH5Bx46+u6QXBiHh36EdXOoIHg8fg8wSWY2UO5Dw+jPoxt7rrEDJhQIo7nAwSjbxIDj5Z1oViQmXM8+VMmkltvrgWzyWaA=
  - secure: T3wEYzZxoChyccN2KwY+zUafzn/+qB6a11WBY6Jtoclf7e7AdtMXbmAm17Ns2iENGLpotRK7MJ2FMBzKQY2+Tu121e5Kb3Vob9+XUW7xdsD45im0QpSdsmomupcYD8zaOdGSexmSPKboLLaL0Xl7BL1UnPRHJHYI3SAnsF4yvd2OfQwMsdZh5slgIPlwixx7TsBZUZdW/EJDfMvV5mLiKcQ/G3oySa57FI8OkYgQ7VR9Vm++j7lJJ+Ol7QyLAAn9MzKZCokJOsqZ/aTX4asWCVRU6KSqKl8dGYEY+gxEXDrJ3GTWCuHLonc9sDTLFGp8FnvPoiXtpwD5+3a6hPUHKlAegeKo1jKYlGeYg4HtLzw3cyVKFy2TPS6cV3zR0Tz1C6HUd8lODIBMOuu2xQjiqnlmJcSjND26zt1BY7PcX5cv/XszQpGYvDGnMg/YeW8AyR2ZegRiaEZOSqUUVE/A2x9iYvHchKG+Zzi8H9/s5BA65LV/l71sqg46gVjYuLpyEr8aCH84P0cX2OuGrI2j+bAF7YIAuwoa6pJNlr3uKDwuBBVnnwRPYlh/vXCFAi/eG8xM/g3VQmSpCv6IFyNmG8Qh75+B/NhKJGgUAlvKEDU6poeUo0xHMfJ+dqxkB3WRLWxO9v5ikCJclJCo181B0RoAPWbU7TSs7zoEXD6qoK0=
before_script:
- npm install -g bower
script: mvn -P docker package
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- export REPO=portlandwebworks/mdhs-poc
- docker tag $REPO $REPO:$TAG
- docker tag $REPO $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
notifications:
  slack:
    secure: QlVFdYZLvYMOiKqnX4Ul65GdSz1+A8pSlogY++41rpGVteiZD8HdzEsXZMNAOi9HutsCAA+zxZxtqgynlu2im0UT2IehFGQNSfaAVRuZwnBzwYUVSGFc2n2w7UZ3XaGjGP3FyarfH2CnnCnfDBQdmnxHzPG1j+6gJlHk0+Yrn4Nh6TTDBeMZg//B4OtYmJ2T5WNio1DabKj1BYCXAJpcloMVK/EGmuKAQxc9UAbkFphjm0ChWzvi2JuFK94Pl81zv6m9jbmiiUYcrkZxSx/OzJec4ETaQsOsqYJwKwqTev2orxpMDBF5zJJpEGulAOhTDTBVF7udYeWrOSzfbja/QbO+3GCPWmOyASb4fROAn3OQPy3szVnuj8NlhCHTRMDDKEKJIaePaSnqiah8G4k6mesmnFHQla/XdN745gg1HxC7qclyRBTI94mtg1UIv/YkM4PW3tD5GixT0WT6nuQrOpj8j0AvLqLc19exa57GNwSJwSaoMgWm3tvK6Rnypb06RSfk4QeAUpG++DJw22oyPdxSOsQjGfOnu/KqIuSInM6jPq//JaW7xCwWrFF4xZBkk8S+/3JWf0/pEwj1GZdkJb6Dor2ZexWlO/lY6XXaUdzoA+MJ7STLVYMtQFlxCfyGrIq56VhebtJqCsmhm3vB0Orggo1fvAn2tGr3M1Dmup0=
