language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - $HOME/.m2
sudo: false
install: true
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_script:
- npm install -g bower
script: mvn install
notifications:
  slack:
    secure: QlVFdYZLvYMOiKqnX4Ul65GdSz1+A8pSlogY++41rpGVteiZD8HdzEsXZMNAOi9HutsCAA+zxZxtqgynlu2im0UT2IehFGQNSfaAVRuZwnBzwYUVSGFc2n2w7UZ3XaGjGP3FyarfH2CnnCnfDBQdmnxHzPG1j+6gJlHk0+Yrn4Nh6TTDBeMZg//B4OtYmJ2T5WNio1DabKj1BYCXAJpcloMVK/EGmuKAQxc9UAbkFphjm0ChWzvi2JuFK94Pl81zv6m9jbmiiUYcrkZxSx/OzJec4ETaQsOsqYJwKwqTev2orxpMDBF5zJJpEGulAOhTDTBVF7udYeWrOSzfbja/QbO+3GCPWmOyASb4fROAn3OQPy3szVnuj8NlhCHTRMDDKEKJIaePaSnqiah8G4k6mesmnFHQla/XdN745gg1HxC7qclyRBTI94mtg1UIv/YkM4PW3tD5GixT0WT6nuQrOpj8j0AvLqLc19exa57GNwSJwSaoMgWm3tvK6Rnypb06RSfk4QeAUpG++DJw22oyPdxSOsQjGfOnu/KqIuSInM6jPq//JaW7xCwWrFF4xZBkk8S+/3JWf0/pEwj1GZdkJb6Dor2ZexWlO/lY6XXaUdzoA+MJ7STLVYMtQFlxCfyGrIq56VhebtJqCsmhm3vB0Orggo1fvAn2tGr3M1Dmup0=
