language: java
jdk:
- oraclejdk8
services:
- docker
cache:
  directories:
  - $HOME/.m2
sudo: false
install: true
env:
  global:
  - secure: LTWl836TLmCVLGsvQ5A46gnTKIbixmOlKl1PrO3tz1t9yVEo2g1/o4omcGrbZLoyBsqwLvORbRoJcd08zy66QoXT/3YC98Jqcn/vmVgvrI27k5gMMrDb4qdhUc5i4tMlTQHnQZ8tGY43bRKkpLA3jZpiFZ6pQQ5RiE7x1ifm2QY9eQ5A1vex88mFrP6xo5Zf8PdICfOtelCUDMiFemAC4BP+3O9RcIWVDJXinVbjOYrm67f4e2zx8XfhfCs49bTFXhtUE81fAhCOV2pNLoa9tCL7Gz+f2OU8I/jy3c12zmwcUIkXc1xSxhYELL5fhI2I3KaiMaCJnY9dYLBEYOideqbApr70vavb5DaIwH7S96HSLNOSQl/ajCGc5gzRk3YoqPAvsWJyFKOhD1zsOqtZbfWG8/zVwjKbUhgS7lg8LsETGkVhVRA1A7tM0BGZIXg+jFEnUYAIbPX8k7vPBtVoECVBVv857L383vfmRqV2pTGEYaxAbqufw5517/sbs+0caX4il19r+abb6oms/f3OD2d07lRXnp4X8pxGZJ6ApnoU54zaqGOv+aqJvVC4vDOOQ1Vde1164Jh4nL2Duk9MtDDrGxvWzmjp0mp9xsE1/Ls78YiIln4sY4p2Hvs96LNnvWiuMpVrljXW5uqujnfQ0N6O2BMKl+sCf8FJm5+RrgU=
  - secure: RYRS+pwvh1Uguhr0QmJA4QH6QeUzqmWw+TkzNPvkehtv4y5ZgyWnCrHqupeHM4b7j5wTiHjwPhL7DgC08IFfQuuqdf8abmN7im50IbvyLfDw3vjnrdJxi8LRJECMj06Ur6AOtLtOYfQ0Evuz9SntsL+hjcx9MGm7/qDW0dEcdaEGcx3fVCMKqLmWCMR9nnfL5VqZrtVM/MA49K7yaUYMr/IZKNJjzcX3FdC4QfpEH/qfL5xiXEFbhqlAnU/MEp6n385bl4QSXeSupiERt6W1Mehaaaxu0q/+g++iLKzgBL11TU7Ta6ZiNaHn00pPAVAIfbi+5z4/PfgoOrLRNvGKN/oYpwWej1r80JMULHq6tHNt6z+ZbsgpNkK/2J+MumCac1v3DXpC8gPau2DyvgXdGSDaEtROz3FedWJhpcqvJYACcodtM/AXrAAXfwkjyV+P0S0avcDlstQ9s7uznSyLbAgO1mVHhtbTlN187qqk5zxEdGHPacvGajkeM+BiIReZ8fxzYvEuVmDrecBby2TP7BVdOO91QvcA+FbpUZvyNaZkYRsHxu5vitG05Us+VYfOLWdEISW/tuWNbmp9go2PPdliGC9tbcZuqqI5jTGP0RQ8Yqvwd036h7ACW1GYKL3GMDkGfGhKrbm11ZKsJAsHmLD128OouUeA22OUfd0KIkM=
  - secure: MrL/ILv4VwHvz4zagboADKHCEXcNhKJxw4rYxfOcdUu+HVHLZ8JkKP+srTYkb/1qcT0J9SFMlIRNvFylJgedqcd48Jn6+0foMeUVh+/mvqty6M+cV8ckAdjmmls6EvcoCfGahUgQJnQLR3/0gfwE5/KmQ6/o1fr0zpA0AZgqFCd12/QE6Hm5ZfiwrncG4jOCpbI/R0SahJ1e0BHsdgexc7m3xK6jHh2ljv4K0DUb606qpd11qOkh4dDqO0CMVgv52bqbjkOjJ6cNiS6GyhezlpWx1nTx/ArYv1freFh+snfElSJwCRO01DI3ghwRtNLZXojJS4urDiMlh4GDRqyqhJmWlooxOT4iXUv0Oo1Es3yszbeCvxf9HfjyiLRnzo30dw3cfZDmVg93ygzQL2FsmFcHnfh8kPHW75nkGBHahsOMfuQn1+WQvatB06C/mJSyAFUfsxbn83pn4pAzYmhOfjk59jbzZCM6+ljn/gUrf5rmKN3RLv4P6PHD1ai+9M0LCXeZqH/VmBjdbk5olzxf9VYSfXgAvNo3bMmcPqUpl7qs86bHuWdfS2NJRwNS3RwW2+rpB3DAe5g0whHMh3a2jrz5kwBBgRKZZu58+G4vrZ9zceNWud4er3V+GWdZKJt/y4VNgvxkT3XmyTFnjBVcVx35XgE+ptuMhBwDdObUK+Q=
before_script:
- npm install -g bower
script: mvn -Ppackage,docker package
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
- export REPO=portlandwebworks/mdhs-poc
- docker tag $REPO $REPO:$TAG
- docker tag $REPO $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
- curl https://sdk.cloud.google.com | bash
- source /home/travis/.bashrc
- gcloud components update kubectl
- kubectl config set-credentials default --username=${GKE_USERNAME} --password=${GKE_PASSWORD}
- kubectl config set-cluster default --server=${GKE_SERVER} --insecure-skip-tls-verify=true
- kubectl config set-context default --cluster=default --user=default
- kubectl config use-context default
- kubectl patch deployment mdhs-deployment -p '{"spec":{"template":{"spec":{"containers":[{"name":"'"webapp"'","image":"'"portlandwebworks/mdhs-poc:travis-$TRAVIS_BUILD_NUMBER"'"}]}}}}'
notifications:
  slack:
    secure: QlVFdYZLvYMOiKqnX4Ul65GdSz1+A8pSlogY++41rpGVteiZD8HdzEsXZMNAOi9HutsCAA+zxZxtqgynlu2im0UT2IehFGQNSfaAVRuZwnBzwYUVSGFc2n2w7UZ3XaGjGP3FyarfH2CnnCnfDBQdmnxHzPG1j+6gJlHk0+Yrn4Nh6TTDBeMZg//B4OtYmJ2T5WNio1DabKj1BYCXAJpcloMVK/EGmuKAQxc9UAbkFphjm0ChWzvi2JuFK94Pl81zv6m9jbmiiUYcrkZxSx/OzJec4ETaQsOsqYJwKwqTev2orxpMDBF5zJJpEGulAOhTDTBVF7udYeWrOSzfbja/QbO+3GCPWmOyASb4fROAn3OQPy3szVnuj8NlhCHTRMDDKEKJIaePaSnqiah8G4k6mesmnFHQla/XdN745gg1HxC7qclyRBTI94mtg1UIv/YkM4PW3tD5GixT0WT6nuQrOpj8j0AvLqLc19exa57GNwSJwSaoMgWm3tvK6Rnypb06RSfk4QeAUpG++DJw22oyPdxSOsQjGfOnu/KqIuSInM6jPq//JaW7xCwWrFF4xZBkk8S+/3JWf0/pEwj1GZdkJb6Dor2ZexWlO/lY6XXaUdzoA+MJ7STLVYMtQFlxCfyGrIq56VhebtJqCsmhm3vB0Orggo1fvAn2tGr3M1Dmup0=
