
spring:
    datasource:
        test-on-borrow: true
        validation-query: SELECT 1;
        url: "jdbc:hsqldb:mem:?shutdown=false"

    jpa:
        hibernate:
            ddl-auto: none
    thymeleaf:
        prefix: "classpath:/templates"
        cache: false
        
logging:
    level:
        com.portlandwebworks: DEBUG
        
liquibase:
    changeLog: "classpath:db/changelog/db.changelog-master.xml"