
apiVersion: v1
kind: Service
metadata:
  name: mdhs-mysql
  labels:
    app: mdhs
spec:
  ports:
    - port: 3306
  selector:
    app: mdhs
    tier: database
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mdhs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mdhs-mysql
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mdhs
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mdhs
              key: mysql.root.password
        #create default database (if does not already exist) using existing spring secrets
        - name: MYSQL_DATABASE
          value: mdhs
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mdhs
              key: spring.datasource.username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mdhs
              key: spring.datasource.password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
