mdhs-mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  environment:
    - MYSQL_DATABASE=mdhs_development
    - MYSQL_USER=myusername
    - MYSQL_PASSWORD=mypassword
    - MYSQL_ROOT_PASSWORD=rootpassword

mdhs-poc:
  image: portlandwebworks/mdhs-poc:latest
  ports:
    - "8080:8080"
  environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://mdhs-mysql:3306/mdhs_development?characterEncoding=UTF-8
    - SPRING_DATASOURCE_USERNAME=myusername
    - SPRING_DATASOURCE_PASSWORD=mypassword
    - SPRING_PROFILES_ACTIVE=
  links:
    - mdhs-mysql
