mdhs-db:
  image: postgres:9.5
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=mdhspass
    - POSTGRES_USER=mdhsuser
    - POSTGRES_DB=mdhs_dev

mdhs-poc:
  image: portlandwebworks/mdhs-poc:latest
  ports:
    - "8080:8080"
  environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://mdhs-db/mdhs_dev
    - SPRING_DATASOURCE_USERNAME=mdhsuser
    - SPRING_DATASOURCE_PASSWORD=mdhspass
    - SPRING_PROFILES_ACTIVE=
  links:
    - mdhs-db
